POST {{loginBaseUrl}}/login/challenge
Content-Type: application/json

{
  "nonce": 1
}

> {%
client.test("Store challenge response and session id", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("challengeResponse", response.body.challenge - 1);
  client.global.set("id", response.body.session_id);
});
%}

###

POST {{loginBaseUrl}}/login/token
Content-Type: application/json

{
  "challenge_response": {{challengeResponse}},
  "session_id": {{id}},
  "email": "{{userId}}",
  "password": "{{password}}"
}

> {%
client.test("Store id token", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("id_token", response.body.id_token);
});
%}

###
