POST {{databaseServiceBaseUrl}}/protected_api/characters
Content-Type: application/json
Authorization: Bearer {{id_token}}

{
    "name": "{{characterName}}",
    "className": "{{characterClass}}"
}

###