POST {{loginServiceBaseUrl}}/public_api/login/token
Content-Type: application/json

{
  "challenge_response": {{response}},
  "session_id": "{{sessionId}}",
  "email": "{{userId}}",
  "password": "{{password}}"
}

###
